#!/usr/bin/env bash
#
# dojo_config.sh (PUBLIC TEMPLATE)
# Configuration file for Danby's Cyber Dojo
# Copy this to ~/.dojo_config.sh and customize for your environment
#
# Generated by: setup_dojo.sh OR manually edited
# No hardcoded values - fully portable

# =========================
# TARGET CONFIGURATION
# =========================
export DOJO_TARGET_HOST="${DOJO_TARGET_HOST:-CHANGE_ME}"   # e.g., 10.0.10.20
export DOJO_TARGET_USER="${DOJO_TARGET_USER:-CHANGE_ME}"   # e.g., ubuntu, admin
export DOJO_TARGET_PORT_SSH="${DOJO_TARGET_PORT_SSH:-22}"

# Optional: SSH config alias (advanced users)
# Example ~/.ssh/config entry:
#   Host dojo-target
#     HostName 10.0.10.20
#     User ubuntu
#     IdentityFile ~/.ssh/dojo_admin
export DOJO_SSH_ALIAS="${DOJO_SSH_ALIAS:-}"  # Leave blank if not using

# =========================
# SSH KEYS (RECOMMENDED)
# =========================
# Separate keys for different purposes (best practice)
export DOJO_KEY_ADMIN="${DOJO_KEY_ADMIN:-$HOME/.ssh/dojo_admin}"
export DOJO_KEY_LOGSYNC="${DOJO_KEY_LOGSYNC:-$HOME/.ssh/dojo_logsync}"
export DOJO_KEY_WATCH="${DOJO_KEY_WATCH:-$HOME/.ssh/dojo_watch}"

# =========================
# LOCAL PATHS
# =========================
# All local data stored here (baselines, captures, logs)
export DOJO_HOME="${DOJO_HOME:-$HOME/cyber_dojo}"

export DOJO_SCRIPTS="${DOJO_SCRIPTS:-$DOJO_HOME/scripts}"
export DOJO_BASELINES="${DOJO_BASELINES:-$DOJO_HOME/baselines}"
export DOJO_CAPTURES="${DOJO_CAPTURES:-$DOJO_HOME/captures}"
export DOJO_LOGS="${DOJO_LOGS:-$DOJO_HOME/logs}"
export DOJO_DIFFS="${DOJO_DIFFS:-$DOJO_HOME/daily_diff}"
export DOJO_SESSIONS="${DOJO_SESSIONS:-$DOJO_HOME/sessions}"

# =========================
# REMOTE LOG PATHS
# =========================
# Standard locations for Ubuntu/Debian systems
export DOJO_LOGS_NGINX_ACCESS="${DOJO_LOGS_NGINX_ACCESS:-/var/log/nginx/access.log}"
export DOJO_LOGS_NGINX_ERROR="${DOJO_LOGS_NGINX_ERROR:-/var/log/nginx/error.log}"
export DOJO_LOGS_AUTH="${DOJO_LOGS_AUTH:-/var/log/auth.log}"
export DOJO_LOGS_GUARDIAN="${DOJO_LOGS_GUARDIAN:-}"  # Optional

# =========================
# HTTP/HTTPS CONFIGURATION
# =========================
# Phase 2.3 - Dual HTTP/HTTPS testing
export DOJO_HTTP_PORT="${DOJO_HTTP_PORT:-80}"
export DOJO_HTTPS_PORT="${DOJO_HTTPS_PORT:-443}"

# Curl options for HTTPS testing (self-signed certs)
# --noproxy '*' = bypass ALL proxies (required for local testing)
# -k = allow self-signed certificates
# -s = silent mode (clean output)
export DOJO_CURL_OPTS="${DOJO_CURL_OPTS:---noproxy '*' -k -s}"

# Timeout for scans (seconds)
export DOJO_TIMEOUT="${DOJO_TIMEOUT:-10}"

# =========================
# COLORS (TERMINAL OUTPUT)
# =========================
export GREEN='\033[0;32m'
export BLUE='\033[0;34m'
export YELLOW='\033[1;33m'
export RED='\033[0;31m'
export NC='\033[0m'  # No Color

# =========================
# HELPER FUNCTIONS
# =========================

# Get SSH target (alias or user@host)
dojo_target() {
  if [[ -n "${DOJO_SSH_ALIAS}" ]]; then
    echo "${DOJO_SSH_ALIAS}"
  else
    echo "${DOJO_TARGET_USER}@${DOJO_TARGET_HOST}"
  fi
}

# Build SSH command with appropriate key
dojo_ssh_base() {
  local key="${1:-$DOJO_KEY_ADMIN}"
  
  # If using SSH alias, defer to ~/.ssh/config
  if [[ -n "${DOJO_SSH_ALIAS}" ]]; then
    echo "ssh ${DOJO_SSH_ALIAS}"
    return 0
  fi
  
  # If key exists, use it
  if [[ -f "${key}" ]]; then
    echo "ssh -i \"${key}\" -p \"${DOJO_TARGET_PORT_SSH}\" -o IdentitiesOnly=yes \"$(dojo_target)\""
  else
    # Fallback to default SSH behavior
    echo "ssh -p \"${DOJO_TARGET_PORT_SSH}\" \"$(dojo_target)\""
  fi
}

# =========================
# VALIDATION
# =========================

# Check if config is initialized
if [[ "${DOJO_TARGET_HOST}" == "CHANGE_ME" ]] || [[ "${DOJO_TARGET_USER}" == "CHANGE_ME" ]]; then
  echo "⚠️  WARNING: Configuration not complete!"
  echo "   Edit ~/.dojo_config.sh or run ./setup_dojo.sh"
fi

# Check if DOJO_HOME exists
if [[ ! -d "${DOJO_HOME}" ]]; then
  echo "⚠️  WARNING: DOJO_HOME not found: ${DOJO_HOME}"
  echo "   Run: mkdir -p ${DOJO_HOME}/{scripts,baselines,captures,logs,daily_diff,sessions}"
fi
