#!/usr/bin/env bash
#
# setup_dojo.sh
# Interactive setup wizard for Danby's Cyber Dojo
# Generates ~/.dojo_config.sh with your environment settings

set -Eeuo pipefail

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Output file
CONFIG_FILE="$HOME/.dojo_config.sh"

echo -e "${BLUE}╔═══════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                       ║${NC}"
echo -e "${BLUE}║   🥋 CYBER DOJO - SETUP WIZARD 🥋    ║${NC}"
echo -e "${BLUE}║                                       ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}This wizard will create your Cyber Dojo configuration.${NC}"
echo ""

# =========================
# COLLECT USER INPUT
# =========================
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}TARGET CONFIGURATION${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

read -rp "Target host (e.g., 10.0.10.20): " TARGET_HOST
read -rp "Target user (e.g., ubuntu): " TARGET_USER
read -rp "SSH port [22]: " SSH_PORT
SSH_PORT="${SSH_PORT:-22}"

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}LOCAL ENVIRONMENT${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

read -rp "Dojo home folder [\$HOME/cyber_dojo]: " DOJO_HOME_INPUT
DOJO_HOME="${DOJO_HOME_INPUT:-$HOME/cyber_dojo}"

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}SSH KEYS (OPTIONAL)${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

read -rp "SSH key for admin access [\$HOME/.ssh/dojo_admin]: " KEY_ADMIN_INPUT
KEY_ADMIN="${KEY_ADMIN_INPUT:-$HOME/.ssh/dojo_admin}"

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}HTTP/HTTPS PORTS${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

read -rp "HTTP port [80]: " HTTP_PORT
HTTP_PORT="${HTTP_PORT:-80}"

read -rp "HTTPS port [443]: " HTTPS_PORT
HTTPS_PORT="${HTTPS_PORT:-443}"

echo ""

# =========================
# GENERATE CONFIG FILE
# =========================
echo -e "${YELLOW}[*] Generating configuration file...${NC}"

cat > "$CONFIG_FILE" <<EOF
#!/usr/bin/env bash
#
# ~/.dojo_config.sh
# Auto-generated by setup_dojo.sh on $(date)
# Danby's Cyber Dojo - Configuration

# =========================
# TARGET CONFIGURATION
# =========================
export DOJO_TARGET_HOST="${TARGET_HOST}"
export DOJO_TARGET_USER="${TARGET_USER}"
export DOJO_TARGET_PORT_SSH="${SSH_PORT}"
export DOJO_SSH_ALIAS=""

# =========================
# SSH KEYS
# =========================
export DOJO_KEY_ADMIN="${KEY_ADMIN}"
export DOJO_KEY_LOGSYNC="\$HOME/.ssh/dojo_logsync"
export DOJO_KEY_WATCH="\$HOME/.ssh/dojo_watch"

# =========================
# LOCAL PATHS
# =========================
export DOJO_HOME="${DOJO_HOME}"
export DOJO_SCRIPTS="\$DOJO_HOME/scripts"
export DOJO_BASELINES="\$DOJO_HOME/baselines"
export DOJO_CAPTURES="\$DOJO_HOME/captures"
export DOJO_LOGS="\$DOJO_HOME/logs"
export DOJO_DIFFS="\$DOJO_HOME/daily_diff"
export DOJO_SESSIONS="\$DOJO_HOME/sessions"

# =========================
# REMOTE LOG PATHS
# =========================
export DOJO_LOGS_NGINX_ACCESS="/var/log/nginx/access.log"
export DOJO_LOGS_NGINX_ERROR="/var/log/nginx/error.log"
export DOJO_LOGS_AUTH="/var/log/auth.log"
export DOJO_LOGS_GUARDIAN=""

# =========================
# HTTP/HTTPS CONFIGURATION
# =========================
export DOJO_HTTP_PORT="${HTTP_PORT}"
export DOJO_HTTPS_PORT="${HTTPS_PORT}"
export DOJO_CURL_OPTS="--noproxy '*' -k -s"
export DOJO_TIMEOUT="10"

# =========================
# COLORS
# =========================
export GREEN='\033[0;32m'
export BLUE='\033[0;34m'
export YELLOW='\033[1;33m'
export RED='\033[0;31m'
export NC='\033[0m'

# =========================
# HELPER FUNCTIONS
# =========================
dojo_target() {
  if [[ -n "\${DOJO_SSH_ALIAS}" ]]; then
    echo "\${DOJO_SSH_ALIAS}"
  else
    echo "\${DOJO_TARGET_USER}@\${DOJO_TARGET_HOST}"
  fi
}

dojo_ssh_base() {
  local key="\${1:-\$DOJO_KEY_ADMIN}"
  if [[ -n "\${DOJO_SSH_ALIAS}" ]]; then
    echo "ssh \${DOJO_SSH_ALIAS}"
    return 0
  fi
  if [[ -f "\${key}" ]]; then
    echo "ssh -i \"\${key}\" -p \"\${DOJO_TARGET_PORT_SSH}\" -o IdentitiesOnly=yes \"\$(dojo_target)\""
  else
    echo "ssh -p \"\${DOJO_TARGET_PORT_SSH}\" \"\$(dojo_target)\""
  fi
}
EOF

chmod 600 "$CONFIG_FILE"

echo -e "${GREEN}✅ Configuration written: ${CONFIG_FILE}${NC}"
echo ""

# =========================
# CREATE DIRECTORY STRUCTURE
# =========================
echo -e "${YELLOW}[*] Creating directory structure...${NC}"

mkdir -p "${DOJO_HOME}"/{scripts,baselines,captures,logs,daily_diff,sessions}

echo -e "${GREEN}✅ Created folders under: ${DOJO_HOME}${NC}"
echo -e "${GREEN}  ├── scripts/${NC}"
echo -e "${GREEN}  ├── baselines/${NC}"
echo -e "${GREEN}  ├── captures/${NC}"
echo -e "${GREEN}  ├── logs/${NC}"
echo -e "${GREEN}  ├── daily_diff/${NC}"
echo -e "${GREEN}  └── sessions/${NC}"
echo ""

# =========================
# COMPLETION
# =========================
echo -e "${BLUE}╔═══════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   SETUP COMPLETE!                     ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}NEXT STEPS:${NC}"
echo ""
echo -e "  1️⃣  Load configuration:"
echo -e "     ${BLUE}source ~/.dojo_config.sh${NC}"
echo ""
echo -e "  2️⃣  Test SSH connection:"
echo -e "     ${BLUE}ssh ${TARGET_USER}@${TARGET_HOST}${NC}"
echo ""
echo -e "  3️⃣  Run baseline capture:"
echo -e "     ${BLUE}./baseline_capture.sh baseline${NC}"
echo ""
echo -e "${GREEN}✅ Your Cyber Dojo is ready!${NC}"
echo ""
